//
// Created by itaylevi on 6/4/19.
//

#ifndef CONCURRENT_WORKSHOP_MASTER_CONSTANTS_H
#define CONCURRENT_WORKSHOP_MASTER_CONSTANTS_H

#define RAND_SEED 0
#define C_CONSTANT 2
#define P_CONSTANT 2

#endif  // CONCURRENT_WORKSHOP_MASTER_CONSTANTS_H
